name: mock_http
description: A Http mock library
version: 3.0.2

environment:
  sdk: ^3.10.1

dependencies: 
  http: ^1.2.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter


